### ISSUE TITLE
Return an exit code other than 0 when duplicate code is found

### ISSUE THREAD

**Issue by trichins** [danielstjules/jsinspect#14]
Can jsinspect return an exit code other than 0 when duplicate code is found?  I'm trying to use jsinspect as part of a git hook and I'm going to stop the commit/push if it finds anything.  Right now, the exit code is always 0 (unless there is an error) and so I have to do some string parsing of the output.

**Comment by danielstjules** [comment]
I was undecided about this before. Only because I wouldn't want a build to be blocked by something silly. But I guess if you've set an appropriate threshold, this wouldn't be an issue.

I'll add a non-zero return status, and just make note in the readme that one can prevent the build from failing by simply using: 
``` bash
jsinspect || true
```

**Comment by danielstjules** [comment]
I actually can't tell if this is a bug, or something I consciously decided on before. Given the bin, it looks like I expected `Inspector.prototype.run` to return the exit status, which it never did. But I've fixed that in https://github.com/danielstjules/jsinspect/commit/2db6a7c61d4e5e391e63b10880c1d4f1eb27f48e Please refer to the latest minor release, 0.5.0.
