### ISSUE TITLE
How to ignore only root node_modules directory

### ISSUE THREAD

**Issue by npasquet** [danielstjules/jsinspect#15]
Hello,

I work on a personal project and use jsinspect.

I wrote my own node modules, when using jsinspect it ignore my folder app/node_modules.

How can ignore only root node_modules directory and still checking my custom modules ?

Best regards,

**Comment by danielstjules** [comment]
Sorry you're hitting this issue! As of right now, there's no way. Since jsinspect doesn't know if you're running the tool from a parent dir, or the project itself, it can't infer what node_modules directory is in the root. So it ignores all node_modules directories.

Imagine the following scenario:
```
$ cd repos
$ ls
repo1
repo2
$ jsinspect .
```

In this case, if jsinspect only ignored the root node_modules, it would start analyzing project1/node_modules as well as project2/node_modules. Which isn't what we want.

Since node_modules is a directory name used specifically by npm, my immediate reaction would be to rename your custom node_modules directory to lib, or something else. It would at least serve as a workaround, since I'm not sure how I'd approach a UI for ignoring some node_modules, but not others.

**Comment by danielstjules** [comment]
After some more thought, I don't think I'll be changing the current behaviour. My suggestion would be to either rename your custom `node_modules` directory to `lib`, or if it makes sense in your case, create packages for each module and individually run jsinspect. The first option is the most straightforward and typical for most projects that I've seen. The second option might make sense if the custom modules are standalone.
