### ISSUE TITLE
Unrecoverable exit status vs duplication found exit status

### ISSUE THREAD

**Issue by nickroth** [danielstjules/jsinspect#37]
Currently, it is possible for a configuration error or file system (e.g. file not found) errors to have the same exit code as if the tool found offending matches. Is it possible for the tool to return a negative result to indicate an unrecoverable error and a positive result to indicate that the tool ran without error but found problems? This should make it easier for users integrating the tool to distinguish problems with an environment or script vs search results from the tool.

**Comment by danielstjules** [comment]
Can you point to examples where negative status codes are found? It's unclear to me how common that approach is, and whether or not it's considered bad style.

Perhaps I shouldn't overload the exit code to report the number of matches herehttps://github.com/danielstjules/jsinspect/blob/master/bin/jsinspect#L113

Instead, a better practice might be:
0 - success (no matches)
1 - any general error
3 - failing to load paths
4 - failing to run jsinspect
5 - failing due to matches being found
