### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by chiptus** [danielstjules/jsinspect#50]
I want to build a webpack loaded for this. What do you think? Maybe a plugin would be more appropriate?

**Comment by danielstjules** [comment]
Not sure! Probably not a loader, since you wouldn't have any tasks that rely on the "transformations" applied by jsinspect (its output). A plugin could maybe make sense if you wanted to constantly write jsinspect's output to some build file automatically. More often than not, it's likely easier to just use it in an npm script.

**Comment by danielstjules** [comment]
Closing for now :)
